services:
    pg:
        build:
            context: .
            dockerfile: pg.Dockerfile
        container_name: pg
        environment:
            POSTGRES_DB: ms2pg
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
        ports:
            - "50000:5432"
        volumes:
            - pg_data:/var/lib/postgresql/data

volumes:
    pg_data:
